all:
  hosts:
    jetsonnano2g:
      ansible_host: 10.7.1.67
    rpi4b8g1:
      ansible_host: 10.7.1.61
    rpi4b8g2:
      ansible_host: 10.7.1.62
    rpi4b8g3:
      ansible_host: 10.7.1.73
  children:
    master:
      hosts:
        jetsonnano2g:
    worker:
      hosts:
        rpi4b8g1:
        rpi4b8g2:
        rpi4b8g3:
  vars:
    target_user: user
    ansible_ssh_user: user
    become_method: sudo
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_local
    ansible_connect: ssh
    timezone: Europe/Brussels
    prometheus_user: prometheus
    prometheus_group: prometheus
    prometheus_port: 9090

