all:
  hosts:
    jetsonnano2g:
      ansible_host: 10.7.1.67
    rpi4b8g1:
      ansible_host: 10.7.1.61
    rpi4b8g2:
      ansible_host: 10.7.1.62
    rpi4b8g3:
      ansible_host: 10.7.1.73
  vars:
    ansible_user: user
    ansible_become_pass: '{{ user_become_pass }}'
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_local
    ansible_connect: ssh
    timezone: Europe/Brussels
    prometheus_user: prometheus
    prometheus_group: prometheus
    prometheus_port: 9090

