---
- hosts: rpi4b8g1
  become: yes
  become_method: sudo
  roles:
    - facts
    - maintenance
    - common
    - arch-repo
    - docker
    - tmux
    - prometheus-node-exporter
    - rpi-eeprom
...
