---
- hosts: rpi4b8g2
  become: yes
  become_method: sudo
  roles:
    - facts
    - maintenance
    - common
    - arch-repo
    - docker
    - tmux
    - prometheus-node-exporter
    - rpi-eeprom
...