- hosts: master
  roles:
    - facts
    - maintenance
    - common
    - docker
    - pihole
    - tmux
    - prometheus-node-exporter
    - prometheus
    - grafana
    - nginx
    - jetson-stats

- hosts: worker
  roles:
    - facts
    - maintenance
    - common
    - arch-repo
    - docker
    - tmux
    - prometheus-node-exporter
    - rpi-eeprom
