---
# tasks file for arch-repo
- name: Comment out geo-based mirror
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: '^Server = http://mirror.archlinuxarm.org'
    replace: '#Server = http://mirror.archlinuxarm.org'
  become: true
  when: ansible_distribution == 'Archlinux'

- name: Uncomment german mirrors 
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: "^# (Server = http://de.*)"
    replace: '\1'
  become: true
  when: ansible_distribution == 'Archlinux'

