---
# tasks file for prometheus-node-exporter

- name: Install prometheus-node-exporter (Arch)
  pacman:
    name: prometheus-node-exporter
    state: latest
  when: ansible_distribution == 'Archlinux'

- name: Create directory for node exporter (Ubuntu/Debian)
  file:
    path: "{{ node_exporter_install_path }}"
    state: directory
    mode: 0755

- name: Install prometheus-node-exporter (Ubuntu/Debian)
  unarchive:
    src: "{{ node_exporter_tarball_url }}"
    dest: "{{ node_exporter_install_path }}"
    extra_opts: [--strip-components=1]
    remote_src: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: copy node_exporter systemd config to server
  template:
    src: "prometheus-node-exporter.service.j2"
    dest: "/etc/systemd/system/prometheus-node-exporter.service"
    mode: "a+x"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Start prometheus-node-exporter service
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: true
    daemon_reload: true
    