---
# tasks file for common

- name: Set locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Update hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone
  timezone:
    name: Europe/Brussels

- lineinfile: 
    dest: /etc/hosts
    state: absent 
    regexp: "^10.7.1.67 jetson-2g"

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: "Create group {{ ansible_user }}"
  group:
    name: "{{ ansible_user }}"
    state: present

- name: "Create user {{ ansible_user }}"
  user:
    name: "{{ ansible_user }}"
    groups: "{{ ansible_user }}"
    state: present
    append: yes

- name: Delete PS1 from bashrc
  lineinfile:
    dest: "/home/{{ ansible_user }}/.bashrc"
    state: absent
    regexp: "^PS1"

- name: bashrc for user
  blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: |
      export IP=$(ifconfig eth0 | grep "inet " | cut -d " " -f 10)

      export PS1="\[\033[0;31m\]\342\224\214\342\224\200$([[ $? != 0 ]] && echo "[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200")[\[\033[1;97m\]\u\[\033[01;33m\]@\[\033[1;94m\]\h\[\033[01;33m\]\[\033[0;31m\]]\342\224\200\[\033[0;31m\][\[\033[1;97m\]"$IP"\[\033[0;31m\]]\342\224\200[\[\033[1;94m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]\[\e[01;33m\]\$\[\e[0m\] "

      export LS_OPTIONS='--color=auto'
      eval "`dircolors`"
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -la'
      alias l='ls $LS_OPTIONS -lA'
      if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
          . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
        fi
      fi

- name: Install dependencies (Ubuntu/Debian)
  apt:
    state: latest
    name:
      - curl
      - wget
      - git
      - silversearcher-ag
      - logrotate
      - ranger
      - htop
      - python3
      - python3-pip
      - jq
      - ncdu
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install dependencies (Arch)
  pacman:
    state: latest
    name:
      - curl
      - wget
      - git
      - the_silver_searcher
      - logrotate
      - ranger
      - bpytop
      - python-pip
      - python3
      - jq
      - ncdu
  when: ansible_distribution == 'Archlinux'

- name: "Define role executed var {{ role_name }}_was_executed"
  set_fact:
    "{{ role_name }}_was_executed": true
    cacheable: true